name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install
        run: npm ci --production=false
      - name: Lint
        run: npx prettier . --check --ignore-unknown
      - name: Build
        run: npm run build
